#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        /usr/bin/aesdsocket-start-stop start
        ;;
    stop)
        echo "Stopping aesdsocket"
        /usr/bin/aesdsocket-start-stop stop
        ;;
    restart|reload)  # Fixed: added pipe character and closing parenthesis
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
