#!/bin/sh

case "$1" in
  start)
    echo "Loading kernel modules from LDD assignment..."
    modprobe hello
    /usr/bin/scull_load
    /usr/bin/module_load faulty
    ;;
  stop)
    echo "Unloading LDD kernel modules..."
    /usr/bin/module_unload faulty
    /usr/bin/scull_unload
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0